seml:
  executable: seml_main.py
  output_dir: ./output_log/slurm/s2nequix
  project_root_dir: ./

slurm:
  - experiments_per_job: 1
    sbatch_options:
      gres: gpu:1 # num GPUs
      mem: 32G # memory
      cpus-per-task: 8 # num cores
      time: 3-00:00 # max time, D-HH:MM
      partition: gpu_a100
      qos: default # default # interactive

fixed:
  profile_device_memory: false
  jax_enable_x64: false
  config_path: "configs/omol25.yml"
  config_override:
    checkpoint_dir: "checkpoints/"
    subset: "spice"
    molsize_range: null
    laplacian_cutoff_interval: [2.0, 10.0]
    num_eigenvectors: 16

grid:
  config_override:
    seed:
      type: choice
      options:
        - 1
        #- 2
        #- 3
